spring:
  datasource:
    username: wuhan
    password: wuhan
    url: jdbc:mysql://18.163.84.216:13306/wuhan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

security:
  jwtSecret: c0406b24d2d3447fa2eecc52f8550a63
  # 一个月
  jwtExpirationInMs: 259200000
